version: '3'

services:
 web:
  build:
   context: .
  ports:
  - 5000:5000
  volumes:
  - ./:/app
  restart: always
  depends_on:
    - mysqldb
  environment:
    FLASK_DEBUG: 1
    FLASK_APP: ./app.py
  # entrypoint:
  #   - flask
  #   - run
  #   - --host=0.0.0.0

 mysqldb:
  image: mysql:8.0.21
  ports:
  - 3344:3306
  environment:
  - MYSQL_ROOT_PASSWORD=manager247
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:

