swagger: '2.0'
info:
  title: News classifier
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json

paths:
  /users:
    post:
      operationId: app.post_users
      summary: Users categories of the given data user
      parameters:
        - name: query
          in: body
          schema:
            type: array
            items:
              $ref: '#/definitions/Query'
      responses:
        200:
          description: Returns user data
          schema:
            type: array
            items:
              $ref: '#/definitions/User'

definitions:
  User:
    type: object
    required:
      - username
      - gender
    properties:
      username:
        type: string
        description: Username of the user
        example: "Ahmad"
        readOnly: true
      gender:
        type: string
        description: Gender of the user
        example: "Laki-laki"
        readOnly: true
  Query:
    type: object
    required:
      - username
      - gender
    properties:
      username:
        type: string
        description: username to User
      gender:
        type: string
        description: gender to User
