swagger: '2.0'
info:
  title: News classifier
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json

paths:
  /users:
    post:
      operationId: user.post_users
      summary: Users categories of the given data user
      parameters:
        - name: query
          in: body
          schema:
            type: array
            items:
              $ref: '#/definitions/QueryUser'
      responses:
        200:
          description: Returns user data
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
  /occupations:
    post:
      operationId: occupation.post_occupation
      summary: Occupation of the given data
      parameters:
        - name: query
          in: body
          schema:
            type: array
            items:
              $ref: '#/definitions/QueryOccupation'
      responses:
        200:
          description: Returns occupation data
          schema:
            type: array
            items:
              $ref: '#/definitions/Occupation'

definitions:
  User:
    type: object
    required:
      - username
      - gender
    properties:
      username:
        type: string
        description: Username of the user
        example: "Ahmad"
        readOnly: true
      gender:
        type: string
        description: Gender of the user
        example: "Laki-laki"
        readOnly: true
  QueryUser:
    type: object
    required:
      - username
      - gender
    properties:
      username:
        type: string
        description: username to User
      gender:
        type: string
        description: gender to User
  Occupation:
    type: object
    required:
      - company_name
      - job
    properties:
      company_name:
        type: string
        description: company_name of the Occupation
        example: "Ahmad"
        readOnly: true
      job:
        type: string
        description: Job of the Occupation
        example: "Programmer"
        readOnly: true
  QueryOccupation:
    type: object
    required:
      - company_name
      - job
    properties:
      username:
        type: string
        description: company_name to Occupation
      job:
        type: string
        description: job to Occupation